// src/data/medicines.js
export const medicineData = [
  {
    name: "Paracetamol",
    generic_name: "Acetaminophen",
    brand_names: "Panadol, Calpol, Tylenol, Febrol",
    company: "GSK Pakistan",
    price_before: "Rs. 50",
    discount: 10,
    price_after: "Rs. 45",
    pack_size: "10 tablets",
    availability: "Available at all pharmacies",
    side_effects: "Rare when taken as directed. May include nausea, rash, or liver damage if overdosed.",
    primary_uses: "Pain relief, Fever reduction, Headache, Body aches",
    description: "Paracetamol is a common painkiller used to treat aches and pain. It can also be used to reduce a high temperature (fever). It's available combined with other painkillers and anti-sickness medicines. It's also an ingredient in a wide range of cold and flu remedies.",
    diseases_treated: "Headache, Migraine, Fever, Muscle pain, Toothache",
    image: "https://5.imimg.com/data5/SELLER/Default/2021/12/QT/VA/JA/3033603/paracetamol-tablets-500x500.jpg",
    dosage: "Adults: 500mg-1g every 4-6 hours (max 4g daily). Children: Based on weight.",
    interactions: "Alcohol increases risk of liver damage. May interact with warfarin.",
    storage: "Store below 30°C in a dry place. Keep out of reach of children.",
    is_prescription: false,
    popular_in_pakistan: true
  },
  {
    name: "Ibuprofen",
    generic_name: "Ibuprofen",
    brand_names: "Brufen, Advil, Motrin",
    company: "Abbott Pakistan",
    price_before: "Rs. 120",
    discount: 15,
    price_after: "Rs. 102",
    pack_size: "10 tablets",
    availability: "Available at most pharmacies",
    side_effects: "Stomach pain, Heartburn, Dizziness, Mild headache",
    primary_uses: "Pain relief, Inflammation reduction, Fever",
    description: "Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID) used to treat mild to moderate pain, and helps to relieve symptoms of arthritis, menstrual cramps, and other conditions.",
    diseases_treated: "Arthritis, Back pain, Toothache, Menstrual cramps",
    image: "https://m.media-amazon.com/images/I/61f+UfS3qoL._SL1500_.jpg",
    dosage: "200-400mg every 4-6 hours as needed (max 1200mg daily)",
    interactions: "May interact with aspirin, blood pressure medications",
    storage: "Store at room temperature away from moisture",
    is_prescription: false,
    popular_in_pakistan: true
  },
  {
    name: "Augmentin",
    generic_name: "Amoxicillin/Clavulanate",
    brand_names: "Augmentin, Clavam, Amoksiklav",
    company: "GlaxoSmithKline Pakistan",
    price_before: "Rs. 350",
    discount: 5,
    price_after: "Rs. 332.50",
    pack_size: "6 tablets",
    availability: "Available at major pharmacies",
    side_effects: "Diarrhea, Nausea, Skin rash, Vaginal itching or discharge",
    primary_uses: "Bacterial infections, Respiratory infections, Urinary tract infections",
    description: "Augmentin is a combination antibiotic containing amoxicillin and clavulanate potassium. It's used to treat many different infections caused by bacteria, such as sinusitis, pneumonia, ear infections, bronchitis, and infections of the skin.",
    diseases_treated: "Sinus infection, Pneumonia, Ear infection, Skin infection",
    image: "https://www.netmeds.com/images/product-v1/600x600/909010/augmentin_625_duo_tablet_6_s_0.jpg",
    dosage: "As prescribed by doctor (typically 1 tablet every 12 hours)",
    interactions: "May interact with blood thinners, other antibiotics",
    storage: "Store below 25°C in a dry place",
    is_prescription: true,
    popular_in_pakistan: true
  },
  {
    name: "Omeprazole",
    generic_name: "Omeprazole",
    brand_names: "Risek, Losec, Omez",
    company: "Getz Pharma Pakistan",
    price_before: "Rs. 200",
    discount: 10,
    price_after: "Rs. 180",
    pack_size: "14 capsules",
    availability: "Available at all pharmacies",
    side_effects: "Headache, Diarrhea, Stomach pain, Nausea",
    primary_uses: "Acid reduction, Heartburn treatment, GERD management",
    description: "Omeprazole is a proton pump inhibitor that decreases the amount of acid produced in the stomach. It's used to treat symptoms of GERD, gastric ulcers, and other conditions involving excessive stomach acid.",
    diseases_treated: "Acidity, Heartburn, GERD, Stomach ulcers",
    image: "https://www.netmeds.com/images/product-v1/600x600/848898/omez_20_capsule_10_s_0.jpg",
    dosage: "20mg once daily before breakfast (or as directed by doctor)",
    interactions: "May interact with clopidogrel, digoxin, antifungal medications",
    storage: "Store below 30°C in original packaging",
    is_prescription: false,
    popular_in_pakistan: true
  },
  {
    name: "Cefixime",
    generic_name: "Cefixime",
    brand_names: "Cefspan, Oroken, Suprax",
    company: "Hilton Pharma Pakistan",
    price_before: "Rs. 400",
    discount: 0,
    price_after: "Rs. 400",
    pack_size: "5 tablets",
    availability: "Available at major pharmacies",
    side_effects: "Diarrhea, Stomach pain, Headache, Dizziness",
    primary_uses: "Bacterial infections, Throat infections, Urinary tract infections",
    description: "Cefixime is a cephalosporin antibiotic that fights bacteria. It's used to treat many different types of infections caused by bacteria, including bronchitis, gonorrhea, and infections of the ears, throat, tonsils, and urinary tract.",
    diseases_treated: "Throat infection, Urinary tract infection, Gonorrhea, Bronchitis",
    image: "https://5.imimg.com/data5/SELLER/Default/2021/12/QT/VA/JA/3033603/paracetamol-tablets-500x500.jpg",
    dosage: "200-400mg daily (or as prescribed by doctor)",
    interactions: "May interact with blood thinners, diuretics",
    storage: "Store below 25°C in a dry place",
    is_prescription: true,
    popular_in_pakistan: true
  },
  {
    name: "Metronidazole",
    generic_name: "Metronidazole",
    brand_names: "Flagyl, Metrogyl, Entizol",
    company: "Sanofi Pakistan",
    price_before: "Rs. 80",
    discount: 5,
    price_after: "Rs. 76",
    pack_size: "10 tablets",
    availability: "Available at all pharmacies",
    side_effects: "Nausea, Headache, Dry mouth, Metallic taste",
    primary_uses: "Bacterial infections, Parasitic infections, Dental infections",
    description: "Metronidazole is an antibiotic that is used to treat a wide variety of infections. It works by stopping the growth of certain bacteria and parasites. It's commonly used for infections of the stomach, skin, joints, and respiratory tract.",
    diseases_treated: "Diarrhea, Dental infection, Stomach infection, Skin infection",
    image: "https://www.netmeds.com/images/product-v1/600x600/848898/omez_20_capsule_10_s_0.jpg",
    dosage: "250-750mg every 8 hours (as prescribed by doctor)",
    interactions: "Avoid alcohol (causes severe reaction), may interact with blood thinners",
    storage: "Store below 30°C in a dry place",
    is_prescription: true,
    popular_in_pakistan: true
  },
  {
    name: "Cetirizine",
    generic_name: "Cetirizine",
    brand_names: "Zyrtec, Alatrol, Cetzine",
    company: "GlaxoSmithKline Pakistan",
    price_before: "Rs. 60",
    discount: 0,
    price_after: "Rs. 60",
    pack_size: "10 tablets",
    availability: "Available at all pharmacies",
    side_effects: "Drowsiness, Fatigue, Dry mouth, Headache",
    primary_uses: "Allergy relief, Itching reduction, Hay fever treatment",
    description: "Cetirizine is an antihistamine that reduces the effects of natural chemical histamine in the body. It's used to treat cold or allergy symptoms such as sneezing, itching, watery eyes, or runny nose.",
    diseases_treated: "Allergies, Hay fever, Hives, Skin itching",
    image: "https://5.imimg.com/data5/SELLER/Default/2021/12/QT/VA/JA/3033603/paracetamol-tablets-500x500.jpg",
    dosage: "10mg once daily (5mg for children)",
    interactions: "May interact with sedatives, other antihistamines",
    storage: "Store below 30°C in a dry place",
    is_prescription: false,
    popular_in_pakistan: true
  },
  {
    name: "Salbutamol",
    generic_name: "Salbutamol",
    brand_names: "Ventolin, Asthalin, Asmol",
    company: "GlaxoSmithKline Pakistan",
    price_before: "Rs. 150",
    discount: 10,
    price_after: "Rs. 135",
    pack_size: "1 inhaler (200 doses)",
    availability: "Available at all pharmacies",
    side_effects: "Tremor, Headache, Palpitations, Muscle cramps",
    primary_uses: "Asthma treatment, Bronchospasm relief, COPD management",
    description: "Salbutamol is a bronchodilator that relaxes muscles in the airways and increases air flow to the lungs. It's used to treat or prevent bronchospasm in people with reversible obstructive airway disease.",
    diseases_treated: "Asthma, Bronchitis, COPD, Exercise-induced bronchospasm",
    image: "https://www.netmeds.com/images/product-v1/600x600/848898/omez_20_capsule_10_s_0.jpg",
    dosage: "1-2 puffs every 4-6 hours as needed (or as directed by doctor)",
    interactions: "May interact with beta-blockers, diuretics, other asthma medications",
    storage: "Store at room temperature away from heat",
    is_prescription: true,
    popular_in_pakistan: true
  },
  {
    name: "Diclofenac Sodium",
    generic_name: "Diclofenac",
    brand_names: "Voltaren, Dicloran, Cataflam",
    company: "Novartis Pakistan",
    price_before: "Rs. 100",
    discount: 5,
    price_after: "Rs. 95",
    pack_size: "10 tablets",
    availability: "Available at all pharmacies",
    side_effects: "Stomach pain, Heartburn, Dizziness, Mild headache",
    primary_uses: "Pain relief, Inflammation reduction, Arthritis treatment",
    description: "Diclofenac is a nonsteroidal anti-inflammatory drug (NSAID) used to treat mild to moderate pain, and helps to relieve symptoms of arthritis, ankylosing spondylitis, and other conditions.",
    diseases_treated: "Arthritis, Back pain, Toothache, Menstrual cramps",
    image: "https://5.imimg.com/data5/SELLER/Default/2021/12/QT/VA/JA/3033603/paracetamol-tablets-500x500.jpg",
    dosage: "50mg 2-3 times daily (or as directed by doctor)",
    interactions: "May interact with blood pressure medications, diuretics, lithium",
    storage: "Store below 30°C in a dry place",
    is_prescription: false,
    popular_in_pakistan: true
  },
  {
    name: "Simvastatin",
    generic_name: "Simvastatin",
    brand_names: "Zocor, Simvor, Simvotin",
    company: "Merck Pakistan",
    price_before: "Rs. 250",
    discount: 10,
    price_after: "Rs. 225",
    pack_size: "10 tablets",
    availability: "Available at major pharmacies",
    side_effects: "Headache, Constipation, Nausea, Muscle pain",
    primary_uses: "Cholesterol reduction, Heart disease prevention",
    description: "Simvastatin is a statin that reduces levels of 'bad' cholesterol (LDL) and triglycerides in the blood, while increasing levels of 'good' cholesterol (HDL). It's used to lower the risk of stroke, heart attack, and other heart complications.",
    diseases_treated: "High cholesterol, Heart disease, Stroke prevention",
    image: "https://www.netmeds.com/images/product-v1/600x600/848898/omez_20_capsule_10_s_0.jpg",
    dosage: "10-40mg once daily in the evening (as prescribed by doctor)",
    interactions: "Avoid grapefruit, may interact with blood thinners, other cholesterol medications",
    storage: "Store below 30°C in original packaging",
    is_prescription: true,
    popular_in_pakistan: true
  }
];